### ISSUE TITLE
Image resolution and caching

### ISSUE THREAD

**Issue by markomitranic** [obrhoff/MusaicFM#34]
Hey there!

Tremendeous job with the screensaver ^^ i am very grateful for it.

So, i was wondering:
1. Could we make a fourth spotify option "Loved Albums" as opposed to "Loved Songs". I don't know if that even makes sense :P
2. More importantly, do you think there is a way to get higher resolution artwork images from Spotify (afaik lastfm offers only low rez) as they look pretty-meh compared to Apple Music's screensaver.
3. Every time it starts, it has to reload all the images. I do not know if it is a network call, or it is just slow. If it is a network call, perhaps we could arrange some local key-based caching.

Anyway. I've never made a screensaver, and I've also never used Spotify APIs. But if you think these features have some merit, I would gladly offer my help and make a PR. :) 

Marko

**Comment by obrhoff** [comment]
Hi, 
about your questions.

1.) I guess it makes sense. Maybe in near future.
2.) Not sure. Actually never checked that out.
3.) Images are cached locally, but there is still a call to the service which may introduce lags. Maybe it would make sense to only fetch once a week for new data. 

Anyway I'm playing with the thought to rewrite everything in Swift one day. Should not take that long but right now I'm busy with stuff.
