### ISSUE TITLE
Unable to sign in on Spotify

### ISSUE THREAD

**Issue by Pixel2407** [obrhoff/MusaicFM#36]
Hey there!

First of all, I really love your screensaver, but there's only one problem I've been facing. I was supposed to sign in on Spotify, but I got a blank screen instead. In other words, I was unable to sign in. Is there another way around this, or it's just a bug that needs fixing?

I hope you get this message in the issue tab, thank you!

P.S. It also hangs System Preferences and I'm currently using a Macbook Pro that runs on macOS Big Sur.

**Comment by obrhoff** [comment]
Hey, sorry for my late reply. I could not reproduce the issue. Do you still have the issue with the latest version?

**Comment by Pixel2407** [comment]
Apparently, it's fixed. Sorry for the late reply, thanks :)
P.S. Sorry if it's a little dumb.
