### ISSUE TITLE
Screensaver content blank

### ISSUE THREAD

**Issue by miacollymoreabbas** [obrhoff/MusaicFM#38]
Hi!

Thank you so so much for this product, in theory, I'd love to use it. Unfortunately, it is showing blank content for me right now. Rather than deal with the tediousness of taking a photo myself, I am attaching a photo from a previous issue discussion board. I've worked with the Spotify API before, I assume they might've just updated or changed something which is annoying. This only happens with the liked songs option though which is one thing. Unfortunately, I don't have many albums saved haha. 
<img width="566" alt="Screen Shot 2021-09-16 at 4 25 02 AM" src="https://user-images.githubusercontent.com/54511558/133587063-c6e48b26-5938-47cb-bf69-56d35aa00604.png">

Thanks again!

**Comment by obrhoff** [comment]
I'm closing this issue, since no one else reported the same problem.

**Comment by miacollymoreabbas** [comment]
Just updated it and it's working properly. Thanks!
