### ISSUE TITLE
Sign in to spotify freezes

### ISSUE THREAD

**Issue by apgigbit** [obrhoff/MusaicFM#39]
When I try to sign into spotify it freezes on the permissions page. Clicking agree or cancel does nothing. It is showing up under apps in spotify.com/account, though. Tried deleting and installing using both methods and removing from apps and re-sign in. 

OS:
macOS Monterey 12.2.1
Apple M1 chip

This is also happening on my intel chip mac.

**Comment by wangjia7758** [comment]
Same problem

**Comment by jeffuntalan** [comment]
Same problem here.

**Comment by obrhoff** [comment]
Okay I fixed the issue with the latest release (1.2.5). Check it out.

**Comment by jeffuntalan** [comment]
Thank you so much. You are a gentleman and a scholar.

**Comment by thew7rst** [comment]
> Okay I fixed the issue with the latest release (1.2.5). Check it out.



> Okay I fixed the issue with the latest release (1.2.5). Check it out.

Thank you!! It's working!
